### ISSUE TITLE
Screenshots in the readme

### ISSUE THREAD

**Issue by bendem** [Gaztin/QDiscord#3]
Hi there, the application looks interesting, could you add screenshots to the README since it's a GUI application, there is really no reason not to have them.

Thanks a bunch.

**Comment by JeppeSRC** [comment]
Maybe you should look again

**Comment by bendem** [comment]
Nevermind...

**Comment by Gaztin** [comment]
QDiscord is not really a GUI application. It's a library written on top of Qt. It does have a couple of sample projects, though, but it's nothing fancy enough to display in the README 😊
