### ISSUE TITLE
Can u make a release so i dont need to build it myself 

### ISSUE THREAD

**Issue by Josee-xav** [Gaztin/QDiscord#5]
title

**Comment by Gaztin** [comment]
Sure! Just to make sure, are on you Windows or Linux? Because those are the only platforms that I've tested on so far.

**Comment by Josee-xav** [comment]
Im on windows  :)

**Comment by Gaztin** [comment]
Here you go https://github.com/Gaztin/QDiscord/releases/tag/1.0
