### ISSUE TITLE
Using in Qt Creator

### ISSUE THREAD

**Issue by brianuuu** [Gaztin/QDiscord#7]
Hi, I'd like to try out this library in Qt Creator, when I tried to add the library in .pro file I can't seem to get it to work with undefined reference compile warnings (I'm not too familiar with adding external libraries with Qt)

Here's what I have added:
LIBS += -L$$PWD/../../QDiscord/lib/windows/x86/release/ -lQDiscord
INCLUDEPATH += $$PWD/../../QDiscord/include
DEPENDPATH += $$PWD/../../QDiscord/include
PRE_TARGETDEPS += $$PWD/../../QDiscord/lib/windows/x86/release/QDiscord.lib

EDIT: manually including the source code and compiling does work however

**Comment by Gaztin** [comment]
Hi! I'm sorry, but this project has not been active for quite some time and thus is sure to be missing a lot of features that the new Discord API provides. I'd suggest looking at other libraries.

I'll archive this repository so as to not mislead people in the future.
